### ISSUE TITLE
First stroke is not drawn

### ISSUE THREAD

**Issue by smidaren** [ZacharyRead/kanjivg-2-animation#1]
When kanji is converted, the first stroke is not drawn. This applies to all kanji.
Fixed by changing:  
if i is not 0:
            svg_build_array.append('<set attributeName="opacity" to="0" dur="' + str(i) + 's" />')

to:
 if i is not 0.0:
            svg_build_array.append('<set attributeName="opacity" to="0" dur="' + str(i) + 's" />')

**Comment by ZacharyRead** [comment]
Thanks for pointing this out. The issue is now corrected!
